# Generated by Django 3.1.4 on 2020-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201212_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
